// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Li7z_KuGBcptoBtry7nltDUK5nyuQ4Y',
    appId: '1:471680982252:web:2a6265dd0c114f1601d9c9',
    messagingSenderId: '471680982252',
    projectId: 'monolithe-sneaker',
    authDomain: 'monolithe-sneaker.firebaseapp.com',
    storageBucket: 'monolithe-sneaker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqH-DoDHmJbTCkSno8X0yza9TUl1CzZeA',
    appId: '1:471680982252:android:d6ddda20fe56af8301d9c9',
    messagingSenderId: '471680982252',
    projectId: 'monolithe-sneaker',
    storageBucket: 'monolithe-sneaker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7s8v6YFoGAAqlE533BjgRh6tyN7rLTOI',
    appId: '1:471680982252:ios:2230340ac60b0a3601d9c9',
    messagingSenderId: '471680982252',
    projectId: 'monolithe-sneaker',
    storageBucket: 'monolithe-sneaker.firebasestorage.app',
    iosBundleId: 'com.monolith.monolith',
  );
}
